---
title: "Models and output for Quiz 05"
format:
  html:
    self-contained: true
    toc: true
    html-math-method: katex
---

The following tables are from [*Beyond Multiple Linear Regression*](https://bookdown.org/roback/bookdown-BeyondMLR/)*.*

```{r}
#| include = FALSE
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
```

## Table 10.4 

```{r, include=FALSE}
Variable <- c("Intercept", "Female", "Married", "Separated or divorced", "Single", "Homeowner", "Latino", "Black", "Mobility", "Age", "Years in neighborhood", "SES", "Concentrated disadvantage", "Immigrant concentration", "Residential stability", "Within neighborhoods", "Between neighborhoods", "Within neighborhoods", "Between neighborhoods")
Coefficient <- c(3.523, -0.012, -0.005, -0.045, -0.026, 0.122, 0.042, -0.029, -0.025, 0.0021, 0.0006, 0.035, -0.172, -0.037, 0.074, 0.320, 0.026, 3.2, 70.3)
SE2 <- c("0.013", "0.015", "0.021", "0.026", "0.024", "0.020", "0.028", "0.030", "0.007", "0.0006", "0.0008", "0.008", "0.016", "0.014", "0.013", " ", " ", " ", " ")
tratio <- c("263.20", "-0.76", "-0.25", "-1.72", "-1.05", "6.04", "1.52", "-0.98", "-3.71", "3.47", "0.78", "4.64", "-10.74", "-2.66", "5.61", " ", " ", " ", " ")
```

```{r, table4chp10, echo=FALSE}
table4chp10 <- data.frame(Variable, Coefficient, SE2, tratio)
colnames(table4chp10) <- c("Variable", "Coefficient", "SE",
                           "t ratio")
table4chp10[6,2] <- paste0(table4chp10[6,2])
table4chp10[10,2] <- paste0(table4chp10[10,2])
table4chp10[12,2] <- paste0(table4chp10[12,2])
table4chp10[14,2] <- paste0(table4chp10[14,2])
table4chp10[15,2] <- paste0(table4chp10[15,2])
kable(table4chp10, booktabs=T, escape=F,
      caption="Correlates of collective efficacy from Table 3 of Sampson et al. (1997).") %>%
  kable_styling(latex_options = "scale_down") %>%
  pack_rows("Person-level predictors", 2, 12) %>%
  pack_rows("Neighborhood-level predictors", 13, 15) %>%
  pack_rows("Variance components", 16, 17) %>%
  pack_rows("Percent of variance explained", 18, 19)
```

## Table 11.4

```{r}
#| include: false
blnkcol <- c("No(ref)", "Yes", "25-34 (ref)", "35-44", "45-54", "55-64", "65-74", "75-84", "Male (ref)", "Female", "2002 (ref)", "2003", "2004", "2005", "2006", "2007")
RR <- c(1.00,2.10,1.00,6.01,19.36,40.29,79.92,178.75,1.00,0.45,
        1.00,1.00,0.97,0.91,0.88,0.88)
CI95 <- c(" ", "1.98-2.23", " ", "5.44-6.64", "17.58-21.31", "36.67-44.26", "72.74-87.80", "162.70-196.39", " ", "0.44-0.45", " ", "0.98-1.03", "0.95-0.99", "0.89-0.94", "0.86-0.91", "0.86-0.91")
Pvalcol <- c("<0.01", " ", "<0.01", " ", " ", " ", " ", " ", "<0.01", " ", "<0.01", " ", " ", " ", " ", " ")
```

```{r}
#| echo: false

table4chp11 <- data.frame(blnkcol, RR, CI95, Pvalcol)
colnames(table4chp11) <- c(" ", "RR", "95% CI", "p-Value")
kable(table4chp11, booktabs=T,
      caption="Adjusted rate ratios for individual-level variables from the multilevel Poisson regression model with random intercept for area from Table 2 in Randall et al. (2014).") %>%
  pack_rows("Aboriginal", 1, 2) %>%
  pack_rows("Age Group", 3, 8) %>%
  pack_rows("Sex", 9, 10) %>%
  pack_rows("Year", 11, 16) %>%
  kable_styling(full_width = F)

```
